### ISSUE TITLE
IndexOutBoundError on removing first column in a table

### ISSUE THREAD

**Issue by skmohit05** [coderazzi/tablefilter-swing#48]
In the attached working example when I try to remove the column at index 1 in the table i get the error in filter code as an array index out of bound.
[Downloads.zip](https://github.com/coderazzi/tablefilter-swing/files/4770373/Downloads.zip)

**Comment by coderazzi** [comment]
Hi, Mohit,
You are modifying the table model without notifying the table of the
change. If you modify the table model, you should issue an event notifying
any listeners of the fact:

model.removeOneColumn();
model.fireTableStructureChanged();

Otherwise, listeners -like the FilterHeader will not know of the changes
you are carrying on...

Best regards,

 L/
